In [2]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [2]:
obj = pd.Series([4,7,-6,5])
obj

0    4
1    7
2   -6
3    5
dtype: int64

In [3]:
obj.values

array([ 4,  7, -6,  5], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4,7,-5,3],index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2['d']

4

In [8]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [10]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [14]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
'b'in obj2

True

In [18]:
sdata = {'Ohio':3500,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata,index=states)
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [23]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [25]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
obj3+obj4

California         NaN
Ohio            7000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [28]:
obj

0    4
1    7
2   -6
3    5
dtype: int64

In [30]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -6
Ryan     5
dtype: int64

In [31]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2003,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2003  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [32]:
#head()只会选中头部的五行
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2003  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [33]:
pd.DataFrame(data,columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2003    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [36]:
frame2 = pd.DataFrame(data,columns = ['year','state','pop','debt'])
frame2.index = ['one','two','three','four','five','six']
frame2 

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2003    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [38]:
frame2['year']

one      2000
two      2001
three    2003
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [39]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [42]:
frame2.loc['three']

year     2003
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [43]:
frame2['debt']=16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2003    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [44]:
#赋值时值的长度必须与dataframe长度一致
frame2['debt']= np.arange(6.)

In [45]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2003    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [46]:
val = pd.Series([-1.2,-1.5,-1.7],index = ['two','four','five'])
frame2['debt']=val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2003    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [47]:
frame2['eastern']=frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2003    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [49]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [11]:
#包含字典的嵌套字典
pop = {'Nevada':{2001:2.4,2002:2.9},
       'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
frame3 = pd.DataFrame(pop)

In [56]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [57]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [68]:
pop = {'Nevada':{2001:2.4,2002:2.9},
       'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
pd.DataFrame(pop,index = [2001,2002,2003])

AttributeError: 'list' object has no attribute 'astype'

In [67]:
pdata = {'Ohio':frame3['Ohio'][:-1],
         'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [13]:
frame3.index.name = 'year';
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [70]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [71]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [4]:
obj = pd.Series(range(3),index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [5]:
index[1:]

Index(['b', 'c'], dtype='object')

In [7]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [8]:
obj2 = pd.Series([1.5,-2.5,0],index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [9]:
obj2.index is labels

True

In [14]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [16]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [17]:
'Ohio' in frame3.columns

True

In [18]:
2003 in frame3.index

False

In [20]:
dup_labels=pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [21]:
#重建索引 reindex
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [22]:
#method='ffill'前向填充，不存在引入缺失值
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [24]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns = ['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [25]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [26]:
states=['Texas','Uath','California']
frame.reindex(columns= states)

Texas  Uath  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [27]:
frame.loc[['a','b','c','d'],states]

D:\Program\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Uath  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [28]:
#轴向删除条目
data = pd.DataFrame(np.arange(16).reshape((4,4)),index = ['Ohio','Colorado','Utah','New York'],
                    columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [29]:
data.drop(['Colorado'])

one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [30]:
data.drop('two',axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [31]:
data.drop(['one','four'],axis = 1)

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [32]:
obj=pd.Series(np.arange(5.),index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [33]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [34]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [36]:
obj.drop('c',inplace = True)

In [37]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [38]:
obj=pd.Series(np.arange(4.),index = ['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [39]:
obj[1:2]

b    1.0
dtype: float64

In [40]:
#series切片包含尾部
obj['a':'c']

a    0.0
b    1.0
c    2.0
dtype: float64

In [41]:
obj['a':'c']=5

In [42]:
obj

a    5.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [43]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index = ['Ohio','Colorado','Utah','New York'],
                    columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [45]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [46]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [47]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [48]:
data[data<5]=0

In [49]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [50]:
#轴标签选择数据
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [51]:
#整数标签选择数据
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [53]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [54]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [58]:
data.iloc[ : , :2][data.two>5]

one  two
Utah        8    9
New York   12   13

In [59]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index = ['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index = ['a','c','e','f','g'])

In [60]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [61]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [62]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [63]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),columns = list('abcde'))

In [64]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [65]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [66]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [67]:
df1.add(df2,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [68]:
df1-df1.iloc[0]

a    b    c    d
0  0.0  0.0  0.0  0.0
1  4.0  4.0  4.0  4.0
2  8.0  8.0  8.0  8.0

In [69]:
df1.sub(df1['d'],axis=0)

a    b    c    d
0 -3.0 -2.0 -1.0  0.0
1 -3.0 -2.0 -1.0  0.0
2 -3.0 -2.0 -1.0  0.0

In [70]:
series2 = pd.Series(range(3),index = ['b','e','f'])
df1+series2

a    b   c   d   e   f
0 NaN  1.0 NaN NaN NaN NaN
1 NaN  5.0 NaN NaN NaN NaN
2 NaN  9.0 NaN NaN NaN NaN

In [71]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns = list('abcd'))

In [72]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [73]:
f = lambda x: x.max() - x.min()
df1.apply(f)

a    8.0
b    8.0
c    8.0
d    8.0
dtype: float64

In [74]:
df1.apply(f,axis = 1)

0    3.0
1    3.0
2    3.0
dtype: float64

In [75]:
df1.apply(f,axis = 0)

a    8.0
b    8.0
c    8.0
d    8.0
dtype: float64

In [78]:
series2 = pd.Series(range(3),index = ['b','f','e'])
series2

b    0
f    1
e    2
dtype: int64

In [79]:
series2.sort_index()

b    0
e    2
f    1
dtype: int64

In [80]:
series3= pd.Series([4,7,3,6])
series3.sort_values()

2    3
0    4
3    6
1    7
dtype: int64

In [81]:
#rank通过将平均排名分配到每个组来打破平级关系
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [82]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [84]:
import pandas_datareader.data as web

In [85]:
all_data = {ticker:web.get_data_yahoo(ticker) for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker:data['Adj Close'] for ticker,data in all_data.items()})
volume = pd.DataFrame({ticker:data['Volume'] for ticker,data in all_data.items()})

In [86]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-05-07 -0.026957 -0.019518 -0.020523 -0.012855
2019-05-08  0.000197  0.002616 -0.000080 -0.006669
2019-05-09 -0.010744 -0.007626 -0.000080 -0.003335
2019-05-10 -0.013853 -0.000148  0.012988  0.001626
2019-05-13 -0.058119 -0.028821 -0.029733 -0.027691

In [87]:
#相关性
returns['MSFT'].corr(returns['IBM'])

0.4867323211619661

In [88]:
#协方差
returns['MSFT'].cov(returns['IBM'])

8.677116893503548e-05

In [89]:
returns.MSFT.corr(returns.IBM)

0.4867323211619661

In [90]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.372831  0.449796  0.457055
IBM   0.372831  1.000000  0.486732  0.404525
MSFT  0.449796  0.486732  1.000000  0.535114
GOOG  0.457055  0.404525  0.535114  1.000000

In [91]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000271  0.000076  0.000107  0.000116
IBM   0.000076  0.000152  0.000087  0.000077
MSFT  0.000107  0.000087  0.000209  0.000120
GOOG  0.000116  0.000077  0.000120  0.000238

In [92]:
returns.corrwith(volume)

AAPL   -0.059361
IBM    -0.155709
MSFT   -0.089318
GOOG   -0.020082
dtype: float64

In [96]:
returns.corrwith(volume,axis = 1)

Date
2009-12-31         NaN
2010-01-04    0.791595
2010-01-05    0.737326
2010-01-06    0.016918
2010-01-07    0.507375
2010-01-08   -0.779512
2010-01-11   -0.351062
2010-01-12   -0.288891
2010-01-13    0.886228
2010-01-14   -0.492768
2010-01-15   -0.290269
2010-01-19    0.903181
2010-01-20    0.281732
2010-01-21   -0.695782
2010-01-22   -0.247709
2010-01-25    0.801915
2010-01-26    0.866175
2010-01-27    0.793799
2010-01-28   -0.903432
2010-01-29   -0.965122
2010-02-01    0.102711
2010-02-02    0.407179
2010-02-03    0.411506
2010-02-04   -0.943247
2010-02-05    0.890386
2010-02-08   -0.362228
2010-02-09    0.452523
2010-02-10   -0.320503
2010-02-11    0.833538
2010-02-12    0.597520
                ...   
2019-04-01   -0.994173
2019-04-02    0.618831
2019-04-03    0.992191
2019-04-04   -0.305824
2019-04-05    0.768019
2019-04-08    0.871958
2019-04-09    0.782447
2019-04-10    0.455621
2019-04-11   -0.849411
2019-04-12   -0.764712
2019-04-15    0.251340
2019-04-16   -0.660717
2019-0

In [97]:
#提取唯一值
obj=pd.Series(['c','a','d','a','a','b','b','c','c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [98]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [99]:
pd.value_counts(obj.values,sort = False)

d    1
b    2
a    3
c    3
dtype: int64

In [100]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [101]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [102]:
to_match = pd.Series(['c','a','b','b','c','a'])
unique_vals = pd.Series(['c','b','a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [103]:
data = pd.DataFrame({'Qu1':[1,2,4,3,4],
                     'Qu2':[2,3,1,2,3],
                     'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    2    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [104]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  1.0  2.0  1.0
3  1.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0